### ISSUE TITLE
Code readability and maintenance

### ISSUE THREAD

**Issue by septa-ma** [Kubis10/CounterForMessenger#32]
In my opinion, there are some ways which can help the code to be manifest:
first one is to change some of the variables name and the second one is using object-oriented-programming for implementing the project.

**Comment by Kubis10** [comment]
Yes, whole language system needs to be rewritten again to English and oop would be good but in tkinter it is kinda difficult when I tried implementing it first time

**Comment by septa-ma** [comment]
Your idea and everything you made is great, and I'm sure your project will be improved in a good way.

**Comment by asimakiskydros** [comment]
Hello, I would like to tackle this issue. My aim is to refactor the entire code's structure while keeping the app's function and look as similar as possible. Let me know if this is something that still interests you, and if you have any advice for me.

**Comment by Kubis10** [comment]
Hi, sure, I would be grateful for any help, because this project has a lot of potential and unfortunately I have little time for it lately. 
If you would like to help refactor the code, I can help if you don't understand something and it would be useful to improve the language system to change the keys to English all files are described in folders so there should be no problem. Thanks
