### ISSUE TITLE
You stole my project logo and name

### ISSUE THREAD

**Issue by ALiangLiang** [Kubis10/CounterForMessenger#65]
Hi friend, thank you for paying attention to my old project, but you use my project’s logo and name without permission. Please change it. I did not attach any open source license to my project.

https://github.com/ALiangLiang/Counter-for-Messenger

**Comment by Kubis10** [comment]
Hey, first of all sorry about the logo and that I didn't contact you, I'll change it. Secondly great job with this plugin I was a big fan of it at the time and that's why when it stopped working I wanted something just for myself and friends who used it but it grew bigger than I thought so sorry for that

**Comment by ALiangLiang** [comment]
Actually, if you can add a description about my project in this project, the logo and name can be used for your non-commercial use.

**Comment by Kubis10** [comment]
I mentioned you in wiki but I can add it to readme too

**Comment by ALiangLiang** [comment]
Okay readme pls. My friend didn't see the wiki when he told me. Finally thank you for liking my old projects :)

**Comment by Kubis10** [comment]
Sure, thanks!

**Comment by ALiangLiang** [comment]
https://github.com/ALiangLiang/Counter-for-Messenger/commit/8619a8a8bef1b4dceb865f46c83508736650dc69

May I recommend your repo over mine?

**Comment by Kubis10** [comment]
It would be an honor for me
